[tool.poetry]
name = "poetry-testi"
version = "0.1.0"
description = ""
authors = ["Kirin Pörsti <kirin.porsti@helsinki.fi>"]

[tool.poetry.dependencies]
python = "^3.8"
cowsay = "^5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
